# Generated by Django 5.2.7 on 2025-11-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetail',
            name='exam_amount',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='examdetail',
            name='created_by',
            field=models.CharField(max_length=100, null=''),
        ),
    ]
