# Generated by Django 5.2.7 on 2025-11-22 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examify', '0002_examdetail_exam_amount_alter_examdetail_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.IntegerField()),
                ('obtained_marks', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('pass_status', models.BooleanField(default=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examify.examdetail')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examify.student_detail')),
            ],
            options={
                'db_table': 'exam_attempt',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examify.examdetail')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examify.questiondetail')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examify.student_detail')),
            ],
            options={
                'db_table': 'student_answer',
            },
        ),
    ]
