# Generated by Django 5.2.7 on 2025-11-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examify', '0003_examattempt_studentanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examattempt',
            name='attempt_number',
            field=models.IntegerField(default=0),
        ),
    ]
